# build stage
FROM node:18-alpine AS build-stage
RUN mkdir /app
WORKDIR /app
COPY package*.json /app/
RUN npm ci --omit=dev

# production stage
FROM node:18-alpine
RUN apk --no-cache add dumb-init
ENV NODE_ENV production
RUN mkdir /app
WORKDIR /app
USER node
COPY --chown=node:node --from=build-stage /app/node_modules /app/node_modules
COPY --chown=node:node . /app
EXPOSE 3000
CMD ["dumb-init", "node", "src/server.js"]
