version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
        environment:
          C_DB_URL: postgres://livemaptestuser:livemaptestpw@localhost

      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: livemaptestuser
          POSTGRES_DB: livemaptestdb
          POSTGRES_PASSWORD: livemaptestpw
    working_directory: ~/repo

    steps:
      - checkout
      
      - run: npm install
 
      - run: npm test
