version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
        environment:
          C_DB_URL: postgres://livemap@localhost:5432/livemapdb

      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install postgresql
      - run: sudo -u postgres psql -p 5432 < initdb/10_init-user-db.sql
      - run: npm install
      - run: npm test
