version: 2.1
orbs:
  docker: circleci/docker@3.0.0
  codecov: codecov/codecov@5.4.3
jobs:
  lint:
    docker:
      - image: cimg/node:24.9.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install -D
      - run:
          name: Run lint
          command: npm run lint
  test:
    docker:
      - image: cimg/node:24.9.0
        environment:
          C_DB_URL: postgres://livemap@localhost:5432/livemapdb
      - image: cimg/postgres:16.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install -D
      - run:
          name: Install PostgreSQL client
          command: |
            sudo apt-get update && sudo apt-get install postgresql-client
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Initialise DB
          command: |
            psql -h localhost -p 5432 -U postgres < initdb/10_init-user-db.sql
      - run:
          name: Create tables
          command: |
            psql -h localhost -p 5432 -U livemap -d livemapdb < setup/schema.sql
      - run:
          name: Run tests
          command: npm run test:coverage
      - codecov/upload:
          files: ./coverage/lcov.info
  deploy-fly-development:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Deploy Fly development
          command: |
            curl -L https://fly.io/install.sh | sh
            export FLYCTL_INSTALL="/home/circleci/.fly"
            export PATH="$FLYCTL_INSTALL/bin:$PATH"
            flyctl auth docker
            DOCKER_BUILDKIT=1 docker build -f Dockerfile.demo -t registry.fly.io/$FLY_APP_NAME_DEV:$CIRCLE_BUILD_NUM .
            docker push registry.fly.io/$FLY_APP_NAME_DEV:$CIRCLE_BUILD_NUM
            flyctl deploy -i registry.fly.io/$FLY_APP_NAME_DEV:$CIRCLE_BUILD_NUM -a $FLY_APP_NAME_DEV
  deploy-fly-demo:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Deploy Fly demo
          command: |
            curl -L https://fly.io/install.sh | sh
            export FLYCTL_INSTALL="/home/circleci/.fly"
            export PATH="$FLYCTL_INSTALL/bin:$PATH"
            flyctl auth docker
            DOCKER_BUILDKIT=1 docker build -f Dockerfile.demo -t registry.fly.io/$FLY_APP_NAME_PROD:$CIRCLE_BUILD_NUM .
            docker push registry.fly.io/$FLY_APP_NAME_PROD:$CIRCLE_BUILD_NUM
            flyctl deploy -i registry.fly.io/$FLY_APP_NAME_PROD:$CIRCLE_BUILD_NUM -a $FLY_APP_NAME_PROD
workflows:
  lint-build-test-deploy:
    jobs:
      - lint
      - test
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1,latest
          dockerfile: Dockerfile.prod
          update_description: true
          use_buildkit: true
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
      - deploy-fly-development:
          requires:
            - lint
            - test
          filters:
            branches:
              ignore: master
      - deploy-fly-demo:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
