version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
        environment:
          C_DB_URL: postgres://livemap:livemap@localhost/livemapdb

      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: livemap
          POSTGRES_DB: livemapdb
          POSTGRES_PASSWORD: livemap
    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install postgresql
      - run: psql < initdb/10_init-user-db.sql
      - run: npm install
      - run: npm test
